{"content": {"suites": {"0": {"status": {"total_pass": 1, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 1, "total_error": 0}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_root", "rerun": "0"}, "1": {"status": "FAIL", "message": "   psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"users_email_key\"\n   DETAIL:  Key (email)=(test2@gmail.com) already exists.\n   sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint \"users_email_key\"\n   DETAIL:  Key (email)=(test2@gmail.com) already exists.\n   \n   [SQL: INSERT INTO users (email, password, company) VALUES (%(email)s, %(password)s, %(company)s) RETURNING users.id]\n   [parameters: {'email': 'test2@gmail.com', 'password': '$2b$12$jXlXFrsiaimT.JcJun.R0uYSrlKCvCD2Kvl.u4mbVyjUYiYHLcDQm', 'company': 'IM'}]\n   (Background on this error at: http://sqlalche.me/e/gkpj)\n", "test_name": "test_create_user", "rerun": "0"}}, "suite_name": "test_users.py"}}}, "date": "June 03, 2022", "start_time": 1654245203, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "1", "fail": "1", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "2"}